run:
  modules-download-mode: readonly
  skip-dirs:
    - .git
    - .github
    - bin
    - dist

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/lukasmalkmus/cwa-qr
  govet:
    check-shadowing: true
  nolintlint:
    allow-unused: false
    allow-leading-space: false
    require-explanation: true
    require-specific: true
