// Code generated by "stringer -type=EventType -linecomment -output=type_string.go"; DO NOT EDIT.

package cwaqr

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[OtherPermanent-1]
	_ = x[OtherTemporary-2]
	_ = x[Retail-3]
	_ = x[FoodService-4]
	_ = x[Craft-5]
	_ = x[Workplace-6]
	_ = x[EducationalInstitution-7]
	_ = x[PublicBuilding-8]
	_ = x[CulturalEvent-9]
	_ = x[ClubActivity-10]
	_ = x[PrivateEvent-11]
	_ = x[WorshipService-12]
}

const _EventType_name = "UnknownOther PermanentOther TemporaryRetailFoodS erviceCraftWorkplaceEducational InstitutionPublic BuildingCultural EventClub ActivityPrivate EventWorship service"

var _EventType_index = [...]uint8{0, 7, 22, 37, 43, 55, 60, 69, 92, 107, 121, 134, 147, 162}

func (i EventType) String() string {
	if i >= EventType(len(_EventType_index)-1) {
		return "EventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EventType_name[_EventType_index[i]:_EventType_index[i+1]]
}
