// Code generated by "stringer -type=TemporaryEventType,PermanentEventType -linecomment -output=type_string.go"; DO NOT EDIT.

package cwaqr

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OtherTemporary-1]
	_ = x[CulturalEvent-2]
	_ = x[ClubActivity-3]
	_ = x[PrivateEvent-4]
	_ = x[WorshipService-5]
}

const _TemporaryEventType_name = "Other TemporaryCultural EventClub ActivityPrivate EventWorship service"

var _TemporaryEventType_index = [...]uint8{0, 15, 29, 42, 55, 70}

func (i TemporaryEventType) String() string {
	i -= 1
	if i >= TemporaryEventType(len(_TemporaryEventType_index)-1) {
		return "TemporaryEventType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _TemporaryEventType_name[_TemporaryEventType_index[i]:_TemporaryEventType_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OtherPermanent-1]
	_ = x[Retail-2]
	_ = x[FoodService-3]
	_ = x[Craft-4]
	_ = x[Workplace-5]
	_ = x[EducationalInstitution-6]
	_ = x[PublicBuilding-7]
}

const _PermanentEventType_name = "Other PermanentRetailFood ServiceCraftWorkplaceEducational InstitutionPublic Building"

var _PermanentEventType_index = [...]uint8{0, 15, 21, 33, 38, 47, 70, 85}

func (i PermanentEventType) String() string {
	i -= 1
	if i >= PermanentEventType(len(_PermanentEventType_index)-1) {
		return "PermanentEventType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _PermanentEventType_name[_PermanentEventType_index[i]:_PermanentEventType_index[i+1]]
}
